name: Build

on: [push, pull_request]

jobs:
  build:
    uses: charmbracelet/meta/.github/workflows/build.yml@main
    with:
      go_version: stable

  snapshot:
    uses: charmbracelet/meta/.github/workflows/snapshot.yml@main
    secrets:
      goreleaser_key: ${{ secrets.GORELEASER_KEY }}

  coverage:
    uses: charmbracelet/meta/.github/workflows/coverage.yml@main
