name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: [~1.17, ^1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - run: go build -v ./...
      - run: go test -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./... -timeout 5m
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
